apiVersion: v1
kind: Pod
metadata:
  generateName: numalign-pod-
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-intel
spec:
  containers:
  - name: numalign
    image: quay.io/fromani/numalign
    imagePullPolicy: IfNotPresent
    command: ["/usr/local/bin/numalign"]
    env:
      - name: NUMALIGN_SLEEP_HOURS
        value: "127"
    resources:
      limits:
        cpu: 2
        memory: 200Mi
        openshift.io/intelnics: 1
      requests:
        cpu: 2
        memory: 200Mi
        openshift.io/intelnics: 1
